name: Unzip File

on:
  push:
    branches:
      - main
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find and unzip files
        run: |
          mkdir extracted
          for file in $(find . -name '*.zip'); do
            unzip -o "$file" -d extracted/
          done

      - name: Upload unzipped files (optional)
        uses: actions/upload-artifact@v4
        with:
          name: unzipped-files
          path: extracted/
